export default food = [
    {   "_id": 0,
        "name": "Batata da Casa",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in elit in diam scelerisque accumsan non sed ante.",
        "imgPath": require('../assets/batata-doce.jpg'),
        "ingredients": [
            { "name": "Batata Doce", "quantity": 1 },
            { "name": "Molho de Alho", "quantity": 1 },
        ],
        "price": 1.29,
        "type": "ent"
    },
    {   "_id": 1,
        "name": "Hamburguer Simplex I",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in elit in diam scelerisque accumsan non sed ante.",
        "imgPath": require('../assets/simplex-1.jpg'),
        "ingredients": [
            { "name": "Hamburguer Vaca", "quantity": 1 },
            { "name": "Tomate Cherry", "quantity": 3 },
            { "name": "Rucúla", "quantity": 1 },
        ],
        "price": 7.99,
        "type": "food"
    },
    {   "_id": 2,
        "name": "Hamburguer Vegan",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in elit in diam scelerisque accumsan non sed ante.",
        "imgPath": require('../assets/vegan.jpg'),
        "ingredients": [
            { "name": "Hamburguer Vegan", "quantity": 1 },
            { "name": "Queijo Suiço", "quantity": 1 },
            { "name": "Alface", "quantity": 1 },
        ],
        "price": 6.49,
        "type": "food"
    },
    {   "_id": 3,
        "name": "Coca-Cola",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in elit in diam scelerisque accumsan non sed ante.",
        "imgPath": require('../assets/cocaCola.jpg'),
        "ingredients": [],
        "price": 1.29,
        "type": "ref"
    },
    {   "_id": 4,
        "name": "Cerveja Sagres",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in elit in diam scelerisque accumsan non sed ante.",
        "imgPath": require('../assets/sagres.jpg'),
        "ingredients": [],
        "price": 1.49,
        "type": "ref"
    },
    {   "_id": 5,
        "name": "Bolo do Caco",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in elit in diam scelerisque accumsan non sed ante.",
        "imgPath": require('../assets/bolo-do-caco.jpg'),
        "ingredients": [],
        "price": 0,
        "type": "pao"
    },
    {   "_id": 6,
        "name": "Pão da Casa",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in elit in diam scelerisque accumsan non sed ante.",
        "imgPath": require('../assets/pao-hamb.jpg'),
        "ingredients": [],
        "price": 0,
        "type": "pao"
    },
]; 